# Generated by Django 4.0.5 on 2022-08-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='seconds_at_borrowing',
            field=models.CharField(default='1660808858.7120986', max_length=24),
        ),
    ]
