# Generated by Django 4.0.5 on 2022-08-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowedbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('borrow_date', models.DateTimeField(auto_now=True)),
                ('seconds_at_borrowing', models.CharField(default='1660835788.1127543', max_length=24)),
                ('borrower_name', models.CharField(default='', max_length=100)),
                ('borrower_email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
